os: Visual Studio 2017
version: 4.0.0.{build}
configuration: Release
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip
install:
  - ps: git clone https://github.com/etsy/statsd.git
  - ps: Start-Process "node" -ArgumentList ".\stats.js .\src\JustEat.StatsD.Tests\statsdconfig.js" -WindowStyle Hidden
  - ps: .\SetAppVeyorBuildVersion.ps1
build_script:
  - ps: .\Build.ps1
artifacts:
- path: '**\$(APPVEYOR_PROJECT_NAME)*.nupkg'
  name: Nuget
test: off
