os: Visual Studio 2017
version: 3.1.1.{build}
configuration: Release
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip
install:
  - ps: .\SetAppVeyorBuildVersion.ps1
build_script:
  - ps: .\Build.ps1
artifacts:
- path: '**\$(APPVEYOR_PROJECT_NAME)*.nupkg'
  name: Nuget
test: off
